FROM nvcr.io/nvidia/nemo:24.07

RUN pip install --no-cache-dir diffusers==0.30.3 git+https://github.com/NVIDIA/NeMo-Run.git av megatron-energon ffmpeg-python==0.2.0 imageio-ffmpeg==0.4.8 imageio==2.26.0 opencv-python==4.8.0.74 opencv-python-headless==4.8.0.74 mediapy
